### ISSUE TITLE
Strengths are evaluated irrespective of conditional statements

### ISSUE THREAD

**Issue by paulyoung** [gss/parser#18]
The following CCSS causes the error `Uncaught (c.RequiredFailure) A required constraint cannot be satisfied`.

``` css
width: == 240 !require;

@if ::window[width] > [breakpoint] {
  width: == 480 !require;
}
```
