### ISSUE TITLE
Comment causes parse issue

### ISSUE THREAD

**Issue by paulyoung** [gss/parser#35]
```css
.post.repost {
  @h |(.block.media)| {
    @v |(&)| in(^);
  }

  .block.media { height: == &intrinsic-height; } // FIXME
}
```

```
Error on line 8, column 1: Expected "/*", "//", ";", comment, end of line or whitespace but "}" found.

7 :   .block.media { height: == &intrinsic-height; } // FIXME
8 : }
^ : ^
9 : 
```
